
import Grid from "@/components/Grid/Grid";
import Head from "next/head";
export default function grid() {
  return (
    <>
      <Head>
        <title>Grid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid/>
    </>
  );
}
